### ISSUE TITLE
Add configuration and automation for local and Travis execution of ITs across fixpacks (Liberty versions)

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/boost-maven#118]
At a high level, we need to consider what testing we need to do for:

1. older levels of Boost vs. newer Liberty/OL versions
2. newer levels of Boost vs. older Liberty/OL versions

1. is fairly obvious, if you don't update the Boost plugin version...

For 2., one scenario is that the LMP under Boost isn't going to reinstall Liberty if it's already there, (without a clean), whereas the ITs are always run against clean directories.

**Comment by chyt** [comment]
Closed by #147.
