### ISSUE TITLE
Failed to run the instruction from Tutorial.md

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/boost-maven#125]
I had no problem to run the <goal>package</goal>
but when run `mvn clean install` with <goal>docker-build</goal>, I got following error:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.064 s
[INFO] Finished at: 2018-09-26T17:27:39-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.openliberty.boost:boost-maven-plugin:0.1:docker-build (default) on 
project gs-spring-boot: Could not build image: java.util.concurrent.ExecutionException: 
javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by chyt** [comment]
Can you run with `-e` to provide full stack trace?

**Comment by gkwan-ibm** [comment]
Here is the [output.txt](https://github.com/OpenLiberty/boost-maven/files/2424370/output.txt)

**Comment by cherylking** [comment]
I see from the attached output that the Dockerfile already exists. Did the project already contain a Dockerfile? If so, can you attach it here? I believe the error you are seeing is related to the contents of the Dockerfile. If no Dockerfile is present, our boost-maven plugin will generate one. You could try renaming the existing Dockerfile to see if our generated one would work for you.

**Comment by gkwan-ibm** [comment]
Dockerfile should be generated by the boost-maven plugin. I cannot attached here. Following is the content:
```
FROM open-liberty:springBoot2 as staging


# The APP_FILE ARG provides the final name of the Spring Boot application archive
ARG APP_FILE


# Stage the fat JAR
COPY target/${APP_FILE} /staging/${APP_FILE}


# Thin the fat application; stage the thin app output and the library cache
RUN springBootUtility thin --sourceAppPath=/staging/${APP_FILE} --targetThinAppPath=/staging/thin-${APP_FILE} --targetLibCachePath=/staging/lib.index.cache


# Final stage, only copying the liberty installation (includes primed caches)
# and the lib.index.cache and thin application
FROM open-liberty:springBoot2


ARG APP_FILE


COPY --from=staging /staging/lib.index.cache /lib.index.cache


COPY --from=staging /staging/thin-${APP_FILE} /config/dropins/spring/thin-${APP_FILE}
```

**Comment by cherylking** [comment]
Could you retry with the 0.1.2-SNAPSHOT of boost-maven? The messages in the Docker related code have been improved since the 0.1 version and do not match the output you provided, making it difficult to deduce what is going on.

**Comment by anjumfatima90** [comment]
Found out that Docker wasn't installed and running on the machine.

**Comment by cherylking** [comment]
Evidently Docker 17.05+ is required. The documentation has been updated with that information in PR #128. If that does not resolve your latest issue, please reopen.
