### ISSUE TITLE
Enforce consistent Java/XML code style - tabs vs. spaces, etc.

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/boost-maven#2]
Perhaps arguable, but to start I'll assume grabbing the Eclipse formatter used in [Open Liberty](https://github.com/OpenLiberty/open-liberty) modules would be a good starting point.

(Also we need to go through the existing (small) codebase and reformat it as a 2nd commit.)

Does this make it less friendly to work outside of Eclipse?

Is there an analogous XML formatter?

**Comment by scottkurz** [comment]
Another idea is to look at this:
https://github.com/revelc/formatter-maven-plugin
which says it formats during the Maven build.

**Comment by uberskigeek** [comment]
Will close this. Will add a new issue to format pom.xml files.
