### ISSUE TITLE
Add profile support plus additional CI coverage - JDK levels, OL vs WLP, versions

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/boost-maven#50]
To build out our matrix we probably need additional profile and/or build properties

**Comment by scottkurz** [comment]
Note with ac6f60327460009bf15388e42b25788bb71420b5  we lost some coverage using runtime artifacts other than OL runtime... 

Though it's at the core a separate issue, maybe we could remember to re-enable along with addressing this issue (or at least stubbing this out somehow).

**Comment by chyt** [comment]
Closed by #147.
