### ISSUE TITLE
Refactor the tests for docker-push

### ISSUE THREAD

**Issue by anjumfatima90** [OpenLiberty/boost-maven#85]
Refactor the tests. Do not assume the first image in the list of docker images to be the final built image. Since `docker-build` goal produces a Dockerfile which uses multi-stage build to build an image and each stage produces an image. That image is stored in the local image cache and the top most image can be the intermediate image instead of the final image. So, loop through the list of images and get the desired final image.

**Comment by chyt** [comment]
Closed by #86.
